### PR TITLE
Add notebook

### PR DESCRIPTION
**Pull request by jennyfothergill**

### CODE REVIEW

**Comment by chrisjonesBSU** [comment]
Couple thoughts after reading through the NB:

1. 
> ..using PlanckTon, which wraps a HOOMD-blue molecular dynamics simulation

The way this is worded is a bit confusing to me. Depending on the reader, "wraps" might not make much sense. Maybe you could use something along the lines of "..which provides a way to easily and reproducibly interface with the HOOMD-blue simulation engine"

2. In the cells with images of the volume and box you mention axis directions in your analysis (e.g. pi-stacking in the y-direction). It might be useful to add axis labels and arrows to these images, especially since the boxes are rotated.

**Comment by chrisjonesBSU** [comment]
I read through it one more time, looks good to me :)

**Review by chrisjonesBSU — APPROVED** [review]

**Comment by jennyfothergill** [comment]
<p>done!</p>

---

 <a href='https://app.reviewnb.com/cmelab/p3ht_validation/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jennyfothergill** [comment]
<p>done!</p>

---

 <a href='https://app.reviewnb.com/cmelab/p3ht_validation/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jennyfothergill** [comment]
<p>I've added an image generated with PeakLabeller. It's an interactive class and can be very messy, so I don't want to call it in this notebook... </p>

---

 <a href='https://app.reviewnb.com/cmelab/p3ht_validation/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jennyfothergill** [comment]
<p>yep, good catch :)</p>

---

 <a href='https://app.reviewnb.com/cmelab/p3ht_validation/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
